### ISSUE TITLE
Is this in a working condition?

### ISSUE THREAD

**Issue by fullstackwebdev** [telehash/teletunnel#1]
Thanks I came across this project when I was tinkering with a similar idea. I downloaded this and fooled around but wasn't able to get it to reply back with a web page. Is this a working version? If so how can I figure out how to get it to work?

**Comment by quartzjer** [comment]
It's close, cc @rynomad for the current status/plans :)

**Comment by rynomad** [comment]
Hey there, sorry for the delay. there's a version installable via npm that's I just realized is in need of a readme. It's working but very buggy. bear with me for another 24 hours and I'll have the latest up on both npm and here, with a readme to boot.

In the meantime, there's two command line utilities that you can use if you run

   npm install teletunnel -g

teletunnel-server -p <port>  // start up a teletunnel server (accepts all clients right now, eventually some sort of auth model will be worked out)
teletunnel -p <local-port> -u <server-url> // expose local-port on <hashname>.server-url.com

there's a bug right now with the subdomain handler I'm using that makes localhost not work correctly... having to do with domain depth, it assumes somthing with a .tld at the end of it. It'll be fixed in the next pass as well, but for now you might want to do add a local.host entry to dnsmasq or similar.

**Comment by rynomad** [comment]
update: 0.0.8 has been published to npm with basic usage docs. Currently the best way to use teletunnel is via the command line, as indicated above. There's a programatic API, to wrap a node http/express server rather than just expose a local port, but it depends on several thtp bugfixes in telehash-js to work properly, which will be rolled out in the next release (0.3.30).
